spring:
  datasource:
    url: ${render.databaseURL}
    username: woofwalkdb_user
    password: ${render.databasePassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0.issuerURI}
  cloud:
    aws:
      region:
        static: eu-north-1

server:
  port: 8080

application:
  bucket:
    name: woof-walk-s3
