spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://dpg-cp7ov3mv3ddc73d93v5g-a.frankfurt-postgres.render.com/woofwalkdb
    username: woofwalkdb_user
    password: cG9XSLtPH7byKOkchHK5PTMMq9OM9EHV
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: dev-h5zqtrdr8n7sgz84.us.auth0.com

server:
  port: 8080
